import base64
import binascii
import datetime
import logging
import uuid

from cryptography.fernet import Fernet, InvalidToken
from pgvector.sqlalchemy import Vector
from sqlalchemy import (
    Boolean,
    DateTime,
    ForeignKey,
    Float,
    Index,
    Integer,
    JSON,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.orm import declarative_base, Mapped, mapped_column, relationship
from sqlalchemy.types import TypeDecorator

from core.config import settings
from core.runtime_secrets import EncryptionKeyRing, build_encryption_keyring

logger = logging.getLogger(__name__)

Base = declarative_base()
FERNET_VALUE_PREFIX = "fernet:v1:"


def _validated_fernet_key() -> bytes:
    if settings.ENCRYPTION_KEY is None:
        raise RuntimeError(
            "ENCRYPTION_KEY is required. Refusing to encrypt without a configured key."
        )

    key = settings.ENCRYPTION_KEY.get_secret_value().encode("utf-8")
    try:
        decoded_key = base64.urlsafe_b64decode(key)
    except (binascii.Error, ValueError) as exc:
        raise RuntimeError(
            "ENCRYPTION_KEY must be a valid Fernet key generated by "
            "Fernet.generate_key()."
        ) from exc
    if len(decoded_key) != 32:
        raise RuntimeError(
            "ENCRYPTION_KEY must be a valid Fernet key generated by "
            "Fernet.generate_key()."
        )
    return key


def get_encryption_keyring() -> EncryptionKeyRing:
    previous_keys = (
        settings.ENCRYPTION_PREVIOUS_KEYS.get_secret_value()
        if settings.ENCRYPTION_PREVIOUS_KEYS is not None
        else None
    )
    return build_encryption_keyring(
        settings.ENCRYPTION_KEY.get_secret_value()
        if settings.ENCRYPTION_KEY is not None
        else None,
        settings.ENCRYPTION_KEY_ID,
        previous_keys,
    )


def get_fernet() -> Fernet:
    return get_encryption_keyring().active_key.fernet


class EncryptedString(TypeDecorator):
    """
    Encrypts string values before saving to the database and decrypts them when
    retrieving.
    Uses Fernet symmetric encryption.
    """

    impl = String
    cache_ok = True

    def process_bind_param(self, value, dialect):
        if value is not None:
            keyring = get_encryption_keyring()
            token = keyring.active_key.fernet.encrypt(value.encode("utf-8")).decode(
                "utf-8"
            )
            return f"{FERNET_VALUE_PREFIX}{keyring.active_key.key_id}:{token}"
        return value

    def process_result_value(self, value, dialect):
        if value is not None:
            keyring = get_encryption_keyring()
            if value.startswith(FERNET_VALUE_PREFIX):
                key_id, _, token = value[len(FERNET_VALUE_PREFIX) :].partition(":")
                encryption_key = keyring.key_for_id(key_id)
                candidate_keys = (encryption_key,) if encryption_key is not None else ()
                ciphertext = token
            else:
                candidate_keys = keyring.all_keys()
                ciphertext = value
            for encryption_key in candidate_keys:
                try:
                    return encryption_key.fernet.decrypt(
                        ciphertext.encode("utf-8")
                    ).decode("utf-8")
                except (InvalidToken, UnicodeDecodeError):
                    continue
            logger.warning("Failed to decrypt field in EncryptedString; returning None")
            return None
        return value


class AuditLog(Base):
    __tablename__ = "audit_logs"

    id: Mapped[int] = mapped_column(primary_key=True)
    timestamp: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
    )
    user_id: Mapped[str] = mapped_column(String, index=True)
    action: Mapped[str] = mapped_column(String)
    resource_type: Mapped[str] = mapped_column(String)
    resource_id: Mapped[str | None] = mapped_column(String, nullable=True)
    details: Mapped[str | None] = mapped_column(Text, nullable=True)


class SecurityAuditEvent(Base):
    __tablename__ = "security_audit_events"

    event_uid: Mapped[str] = mapped_column(
        String, default=lambda: uuid.uuid4().hex, primary_key=True
    )
    actor_user_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    actor_role: Mapped[str] = mapped_column(String, index=True, nullable=False)
    organization_id: Mapped[str | None] = mapped_column(String, index=True, nullable=True)
    workspace_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    event_action: Mapped[str] = mapped_column(String, index=True, nullable=False)
    resource_type: Mapped[str] = mapped_column(String, index=True, nullable=False)
    resource_uid: Mapped[str | None] = mapped_column(String, index=True, nullable=True)
    evidence_source: Mapped[str] = mapped_column(String, nullable=False)
    detail_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    observed_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
        index=True,
    )
    __table_args__ = (
        Index(
            "ix_security_audit_events_scope_time",
            "organization_id",
            "workspace_id",
            "observed_at",
        ),
        Index(
            "ix_security_audit_events_actor_scope",
            "actor_user_id",
            "organization_id",
            "workspace_id",
        ),
    )

class LLMProvider(Base):
    __tablename__ = "llm_providers"
    __table_args__ = (
        UniqueConstraint(
            "organization_id",
            "name",
            name="uq_llm_providers_org_name",
        ),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    organization_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    name: Mapped[str] = mapped_column(String, index=True)
    provider_type: Mapped[str] = mapped_column(
        String
    )  # e.g. openai, anthropic, gemini, ollama
    base_url: Mapped[str | None] = mapped_column(String, nullable=True)
    model_identifier: Mapped[str | None] = mapped_column(String, nullable=True)
    embedding_model: Mapped[str | None] = mapped_column(String, nullable=True)
    api_key: Mapped[str | None] = mapped_column(EncryptedString, nullable=True)
    is_active: Mapped[bool] = mapped_column(Boolean, default=False)
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
        onupdate=lambda: datetime.datetime.now(datetime.timezone.utc),
    )


class ScopeweavePromotionTarget(Base):
    """Per-workspace scopeweave instance the promote action pushes work items to.

    The ``base_url`` is validated against ``ALLOWED_SCOPEWEAVE_HOSTS`` at runtime
    and the personal access token is stored Fernet-encrypted, mirroring how
    ``LLMProvider`` keeps its ``api_key``. Config is resolved from the database
    at request time (never from ``os.getenv``).
    """

    __tablename__ = "scopeweave_promotion_target"
    __table_args__ = (
        UniqueConstraint(
            "organization_id",
            "workspace_id",
            name="uq_scopeweave_promotion_target_scope",
        ),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    organization_id: Mapped[str | None] = mapped_column(
        String, index=True, nullable=True
    )
    workspace_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    base_url: Mapped[str] = mapped_column(String, nullable=False)
    access_token: Mapped[str] = mapped_column(EncryptedString, nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
        nullable=False,
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
        onupdate=lambda: datetime.datetime.now(datetime.timezone.utc),
        nullable=False,
    )


class ScopeweavePromotionLink(Base):
    """Mapping of a naruon project-graph object to its scopeweave work item.

    One row per promoted ``object_uid`` within a workspace; re-promoting updates
    the same row so the citation-carrying link between naruon evidence and the
    scopeweave work item stays stable and idempotent.
    """

    __tablename__ = "scopeweave_promotion_link"
    __table_args__ = (
        UniqueConstraint(
            "workspace_id",
            "object_uid",
            name="uq_scopeweave_promotion_link_object",
        ),
        Index(
            "ix_scopeweave_promotion_link_scope",
            "organization_id",
            "workspace_id",
            "project_uid",
        ),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    organization_id: Mapped[str | None] = mapped_column(
        String, index=True, nullable=True
    )
    workspace_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    project_uid: Mapped[str] = mapped_column(String, index=True, nullable=False)
    object_uid: Mapped[str] = mapped_column(String, index=True, nullable=False)
    object_type: Mapped[str] = mapped_column(String, nullable=False)
    scopeweave_work_item_id: Mapped[str] = mapped_column(String, nullable=False)
    scopeweave_work_item_url: Mapped[str | None] = mapped_column(
        String, nullable=True
    )
    promoted_confidence: Mapped[float] = mapped_column(Float, nullable=False)
    citation_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    promoted_by_user_id: Mapped[str] = mapped_column(String, nullable=False)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
        nullable=False,
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
        onupdate=lambda: datetime.datetime.now(datetime.timezone.utc),
        nullable=False,
    )


class NewsdomProvider(Base):
    """NewsDOM PDF DOM recognition sidecar credentials.

    Mirrors :class:`LLMProvider`: the base URL is stored in plaintext while the
    bearer token is encrypted at rest via :class:`EncryptedString` (Fernet).
    Consumer code reads these values from the database — never from
    ``os.getenv`` at request time — so the sidecar can be (re)configured per
    organization without redeploying the API.
    """

    __tablename__ = "newsdom_providers"
    __table_args__ = (
        UniqueConstraint(
            "organization_id",
            "provider_name",
            name="uq_newsdom_providers_org_name",
        ),
    )

    newsdom_provider_id: Mapped[int] = mapped_column(
        "newsdom_provider_id", primary_key=True
    )
    user_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    organization_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    provider_name: Mapped[str] = mapped_column(String, index=True, nullable=False)
    base_url: Mapped[str | None] = mapped_column(String, nullable=True)
    api_token: Mapped[str | None] = mapped_column(EncryptedString, nullable=True)
    request_language: Mapped[str] = mapped_column(
        String(32), default="auto", nullable=False
    )
    recognition_mode: Mapped[str] = mapped_column(
        String(32), default="auto", nullable=False
    )
    is_active: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
        onupdate=lambda: datetime.datetime.now(datetime.timezone.utc),
    )


class WorkspaceRunnerConfig(Base):
    __tablename__ = "workspace_runner_configs"

    id: Mapped[int] = mapped_column(primary_key=True)
    organization_id: Mapped[str] = mapped_column(String, unique=True, index=True)
    workspace_id: Mapped[str] = mapped_column(String, unique=True, index=True)
    registration_token: Mapped[str | None] = mapped_column(
        EncryptedString, nullable=True
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
        onupdate=lambda: datetime.datetime.now(datetime.timezone.utc),
    )


class ConnectorSignalEvent(Base):
    __tablename__ = "connector_signal_events"

    event_uid: Mapped[str] = mapped_column(
        String,
        primary_key=True,
        default=lambda: f"connector_evt_{uuid.uuid4().hex}",
    )
    organization_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    workspace_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    signal_key: Mapped[str] = mapped_column(String, index=True, nullable=False)
    state_code: Mapped[str] = mapped_column(String, index=True, nullable=False)
    detail_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    observed_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
        nullable=False,
    )
    __table_args__ = (
        Index(
            "ix_connector_signal_events_scope_time",
            "organization_id",
            "workspace_id",
            "observed_at",
        ),
    )


class ProviderWritebackRetryItem(Base):
    __tablename__ = "provider_writeback_retry_items"

    retry_item_uid: Mapped[str] = mapped_column(
        String,
        primary_key=True,
        default=lambda: f"provider_retry_{uuid.uuid4().hex}",
    )
    organization_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    workspace_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    source_uid: Mapped[str | None] = mapped_column(String, index=True, nullable=True)
    command_action: Mapped[str] = mapped_column(String, index=True, nullable=False)
    command_payload_encrypted: Mapped[str] = mapped_column(
        EncryptedString,
        nullable=False,
    )
    retry_state: Mapped[str] = mapped_column(
        String,
        index=True,
        default="pending",
        nullable=False,
    )
    last_error_code: Mapped[str] = mapped_column(String, index=True, nullable=False)
    runner_request_uid: Mapped[str | None] = mapped_column(
        String,
        index=True,
        nullable=True,
    )
    attempt_count: Mapped[int] = mapped_column(Integer, default=1, nullable=False)
    next_retry_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        index=True,
        nullable=False,
    )
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
        nullable=False,
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
        onupdate=lambda: datetime.datetime.now(datetime.timezone.utc),
        nullable=False,
    )
    __table_args__ = (
        Index(
            "ix_provider_writeback_retry_items_scope_state",
            "organization_id",
            "workspace_id",
            "retry_state",
            "next_retry_at",
        ),
        Index(
            "ix_provider_writeback_retry_items_source_action",
            "source_uid",
            "command_action",
        ),
    )


class LlmBatchJob(Base):
    """A batch-tolerant embedding job routed through contextual-orchestrator.

    naruon-side control-plane record for one bulk, latency-tolerant embedding
    run (e.g. an email-import batch). The *primary* execution path submits the
    batch to the ``contextual-orchestrator`` batch API, which owns provider
    routing, load balancing and cost accounting and forwards the work to
    ``pg-llm-batch``. naruon keeps this durable audit trail (which path served
    the batch, the orchestrator's batch id, the reported cost) so batch work is
    observable even though the routing/cost decisions live in the orchestrator.
    Modeled on :class:`ProviderWritebackRetryItem` (string uid PK, scope
    indexes).
    """

    __tablename__ = "llm_batch_jobs"

    batch_job_uid: Mapped[str] = mapped_column(
        String,
        primary_key=True,
        default=lambda: f"llm_batch_{uuid.uuid4().hex}",
    )
    organization_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    user_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    job_status: Mapped[str] = mapped_column(
        String,
        index=True,
        default="preparing",
        nullable=False,
    )
    # "orchestrator" (primary) or "local_engine" (offline dev fallback).
    routing_mode: Mapped[str | None] = mapped_column(String, index=True, nullable=True)
    model_name: Mapped[str] = mapped_column(String, nullable=False)
    endpoint_alias: Mapped[str | None] = mapped_column(String, nullable=True)
    # The batch id assigned by contextual-orchestrator (None for local runs).
    orchestrator_batch_uid: Mapped[str | None] = mapped_column(
        String, index=True, nullable=True
    )
    total_items: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    completed_items: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    failed_items: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    total_tokens: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    part_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    # Cost as reported by the orchestrator, in micro-USD (1e-6 USD), or None.
    cost_micro_usd: Mapped[int | None] = mapped_column(Integer, nullable=True)
    error_code: Mapped[str | None] = mapped_column(String, nullable=True)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
        nullable=False,
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
        onupdate=lambda: datetime.datetime.now(datetime.timezone.utc),
        nullable=False,
    )
    items: Mapped[list["LlmBatchItem"]] = relationship(
        back_populates="job",
        cascade="all, delete-orphan",
    )
    __table_args__ = (
        Index(
            "ix_llm_batch_jobs_scope_status",
            "organization_id",
            "user_id",
            "job_status",
        ),
    )


class LlmBatchItem(Base):
    """A single input within an :class:`LlmBatchJob`.

    One item per input text, carrying its token count and the partition (batch
    file part) it was assigned to — reported by the orchestrator on the primary
    path, or by the ``pg-llm-batch`` accumulator on the local fallback path.
    """

    __tablename__ = "llm_batch_items"

    batch_item_uid: Mapped[str] = mapped_column(
        String,
        primary_key=True,
        default=lambda: f"llm_batch_item_{uuid.uuid4().hex}",
    )
    batch_job_uid: Mapped[str] = mapped_column(
        String,
        ForeignKey("llm_batch_jobs.batch_job_uid", ondelete="CASCADE"),
        index=True,
        nullable=False,
    )
    sequence_no: Mapped[int] = mapped_column(Integer, nullable=False)
    part_index: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    token_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    item_status: Mapped[str] = mapped_column(
        String,
        index=True,
        default="queued",
        nullable=False,
    )
    error_code: Mapped[str | None] = mapped_column(String, nullable=True)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
        nullable=False,
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
        onupdate=lambda: datetime.datetime.now(datetime.timezone.utc),
        nullable=False,
    )
    job: Mapped["LlmBatchJob"] = relationship(back_populates="items")
    __table_args__ = (
        Index(
            "ix_llm_batch_items_job_sequence",
            "batch_job_uid",
            "sequence_no",
        ),
    )


class Organization(Base):
    __tablename__ = "organization_entities"

    id: Mapped[str] = mapped_column(String, primary_key=True)
    name: Mapped[str | None] = mapped_column(String, nullable=True)

    groups: Mapped[list["OrganizationGroup"]] = relationship(
        back_populates="organization"
    )
    role_assignments: Mapped[list["ScopedRoleAssignment"]] = relationship(
        back_populates="organization"
    )


class OrganizationGroup(Base):
    __tablename__ = "organization_groups"

    id: Mapped[str] = mapped_column(String, primary_key=True)
    organization_id: Mapped[str] = mapped_column(
        ForeignKey("organization_entities.id"), index=True
    )
    name: Mapped[str | None] = mapped_column(String, nullable=True)

    organization: Mapped["Organization"] = relationship(back_populates="groups")
    role_assignments: Mapped[list["ScopedRoleAssignment"]] = relationship(
        back_populates="group"
    )


class ScopedRoleAssignment(Base):
    __tablename__ = "scoped_role_assignments"

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[str] = mapped_column(String, index=True)
    role: Mapped[str] = mapped_column(String, index=True)
    organization_id: Mapped[str | None] = mapped_column(
        ForeignKey("organization_entities.id"), nullable=True, index=True
    )
    group_id: Mapped[str | None] = mapped_column(
        ForeignKey("organization_groups.id"), nullable=True, index=True
    )

    organization: Mapped["Organization | None"] = relationship(
        back_populates="role_assignments"
    )
    group: Mapped["OrganizationGroup | None"] = relationship(
        back_populates="role_assignments"
    )


class PromptTemplate(Base):
    __tablename__ = "prompt_templates"
    __table_args__ = (
        Index(
            "ix_prompt_templates_owner_scope",
            "created_by",
            "organization_id",
            "workspace_id",
        ),
        Index(
            "ix_prompt_templates_shared_scope",
            "organization_id",
            "workspace_id",
            "is_shared",
        ),
    )


    id: Mapped[int] = mapped_column(primary_key=True)
    prompt_uid: Mapped[str] = mapped_column(
        String,
        unique=True,
        index=True,
        default=lambda: f"prompt_{uuid.uuid4().hex}",
        nullable=False,
    )
    title: Mapped[str] = mapped_column(String, index=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    content: Mapped[str] = mapped_column(Text)
    is_shared: Mapped[bool] = mapped_column(Boolean, default=False)
    created_by: Mapped[str] = mapped_column(String, index=True)
    organization_id: Mapped[str | None] = mapped_column(
        String, index=True, nullable=True
    )
    workspace_id: Mapped[str | None] = mapped_column(String, index=True, nullable=True)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
        onupdate=lambda: datetime.datetime.now(datetime.timezone.utc),
    )


class WorkflowDefinition(Base):
    __tablename__ = "workflow_definitions"
    __table_args__ = (
        Index(
            "ix_workflow_definitions_scope_time",
            "organization_id",
            "workspace_id",
            "updated_at",
        ),
        Index(
            "ix_workflow_definitions_owner_scope",
            "user_id",
            "organization_id",
            "workspace_id",
            "updated_at",
        ),
    )

    workflow_uid: Mapped[str] = mapped_column(
        String,
        primary_key=True,
        default=lambda: f"workflow_{uuid.uuid4().hex}",
        nullable=False,
    )
    organization_id: Mapped[str] = mapped_column(String, nullable=False)
    workspace_id: Mapped[str] = mapped_column(String, nullable=False)
    user_id: Mapped[str] = mapped_column(String, nullable=False)
    workflow_name: Mapped[str] = mapped_column(String, nullable=False)
    workflow_description: Mapped[str | None] = mapped_column(Text, nullable=True)
    steps_json: Mapped[list[dict[str, object]]] = mapped_column(
        JSON, default=list, nullable=False
    )
    state_code: Mapped[str] = mapped_column(
        String, default="draft", nullable=False
    )
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
        nullable=False,
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
        onupdate=lambda: datetime.datetime.now(datetime.timezone.utc),
        nullable=False,
    )

    agent_run_records: Mapped[list["AgentRunRecord"]] = relationship(
        back_populates="workflow_definition"
    )


class AgentRunRecord(Base):
    __tablename__ = "agent_run_records"
    __table_args__ = (
        Index("ix_agent_run_records_workflow_uid", "workflow_uid"),
        Index(
            "ix_agent_run_records_scope_time",
            "organization_id",
            "workspace_id",
            "started_at",
        ),
        Index(
            "ix_agent_run_records_owner_scope",
            "user_id",
            "organization_id",
            "workspace_id",
            "started_at",
        ),
        Index(
            "ix_agent_run_records_workflow_time",
            "workflow_uid",
            "started_at",
        ),
    )

    run_uid: Mapped[str] = mapped_column(
        String,
        primary_key=True,
        default=lambda: f"agent_run_{uuid.uuid4().hex}",
        nullable=False,
    )
    workflow_uid: Mapped[str] = mapped_column(
        ForeignKey("workflow_definitions.workflow_uid"), nullable=False
    )
    organization_id: Mapped[str] = mapped_column(String, nullable=False)
    workspace_id: Mapped[str] = mapped_column(String, nullable=False)
    user_id: Mapped[str] = mapped_column(String, nullable=False)
    status_code: Mapped[str] = mapped_column(
        String, default="pending", nullable=False
    )
    started_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
        nullable=False,
    )
    completed_at: Mapped[datetime.datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    result_summary: Mapped[str | None] = mapped_column(Text, nullable=True)

    workflow_definition: Mapped["WorkflowDefinition"] = relationship(
        back_populates="agent_run_records"
    )


class Email(Base):
    __tablename__ = "email_records"

    __table_args__ = (
        UniqueConstraint(
            "user_id",
            "organization_id",
            "message_id",
            name="uq_emails_owner_message_id",
        ),
        Index(
            "ix_email_records_owner_date",
            "user_id",
            "organization_id",
            "date",
        ),
    )

    @classmethod
    def owner_filters(cls, user_id: str, organization_id: str | None):
        organization_filter = (
            cls.organization_id == organization_id
            if organization_id is not None
            else cls.organization_id.is_(None)
        )
        return (cls.user_id == user_id, organization_filter)

    id: Mapped[int] = mapped_column(primary_key=True)
    # Owner scope columns are intentionally plaintext and indexed: signed-session
    # ABAC filters must be enforced by SQL before email rows are returned.
    user_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    organization_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    message_id: Mapped[str] = mapped_column(String, index=True)
    thread_id: Mapped[str | None] = mapped_column(
        String, index=True, nullable=True
    )  # O3: email threading support
    fingerprint: Mapped[str | None] = mapped_column(
        String, index=True, nullable=True
    )
    sender: Mapped[str] = mapped_column(String)
    reply_to: Mapped[str | None] = mapped_column(String, nullable=True)
    recipients: Mapped[str | None] = mapped_column(String, nullable=True)
    subject: Mapped[str | None] = mapped_column(String, nullable=True)
    in_reply_to: Mapped[str | None] = mapped_column(String, nullable=True)
    references: Mapped[str | None] = mapped_column(String, nullable=True)
    date: Mapped[datetime.datetime] = mapped_column(DateTime(timezone=True), index=True)
    body: Mapped[str] = mapped_column(Text)
    # IMAP \Seen read state; defaults read so historical/file imports don't nag.
    is_read: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    # Defer large pgvector payloads on default entity loads.
    embedding = mapped_column(Vector(1536), deferred=True)
    attachments: Mapped[list["Attachment"]] = relationship(
        back_populates="email", cascade="all, delete-orphan"
    )
    content_nodes: Mapped[list["ContentNodeRecord"]] = relationship(
        back_populates="email", cascade="all, delete-orphan"
    )
    content_segments: Mapped[list["ContentSegmentRecord"]] = relationship(
        back_populates="email"
    )
    knowledge_graph_edges: Mapped[list["KnowledgeGraphEdgeRecord"]] = relationship(
        back_populates="email", cascade="all, delete-orphan"
    )
    ticket_tasks: Mapped[list["TicketTask"]] = relationship(
        back_populates="related_email", cascade="all, delete-orphan"
    )


class TicketTask(Base):
    __tablename__ = "ticket_tasks"

    id: Mapped[int] = mapped_column("task_id", primary_key=True)
    task_uid: Mapped[str] = mapped_column(
        String(32), default=lambda: uuid.uuid4().hex, unique=True, index=True
    )
    user_id: Mapped[str] = mapped_column(String, index=True)
    organization_id: Mapped[str | None] = mapped_column(
        String, index=True, nullable=True
    )
    title: Mapped[str] = mapped_column("task_title", String)
    status: Mapped[str] = mapped_column(
        "status_code", String, default="open", index=True
    )
    priority: Mapped[str] = mapped_column(
        "priority_code", String, default="normal", index=True
    )
    source_type: Mapped[str] = mapped_column(String, default="email", index=True)
    related_email_id: Mapped[int | None] = mapped_column(
        "email_id", ForeignKey("email_records.id"), nullable=True, index=True
    )
    related_thread_id: Mapped[str | None] = mapped_column(
        "thread_id", String, nullable=True, index=True
    )
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
        onupdate=lambda: datetime.datetime.now(datetime.timezone.utc),
    )

    related_email: Mapped["Email | None"] = relationship(back_populates="ticket_tasks")


Index(
    "uq_ticket_tasks_reply_sla_email",
    TicketTask.user_id,
    func.coalesce(TicketTask.organization_id, ""),
    TicketTask.source_type,
    TicketTask.related_email_id,
    unique=True,
    postgresql_where=(
        (TicketTask.source_type == "reply_sla")
        & (TicketTask.related_email_id.is_not(None))
    ),
)


class Attachment(Base):
    __tablename__ = "email_attachments"

    id: Mapped[int] = mapped_column(primary_key=True)
    email_id: Mapped[int] = mapped_column(ForeignKey("email_records.id"))
    filename: Mapped[str] = mapped_column(String)
    content: Mapped[str] = mapped_column(Text)
    content_type: Mapped[str] = mapped_column(
        String(120), default="text/plain", nullable=False
    )
    parse_status: Mapped[str] = mapped_column(
        String(64), default="parsed", nullable=False
    )
    parse_content_type: Mapped[str] = mapped_column(
        String(120), default="text/plain", nullable=False
    )
    parser_key: Mapped[str] = mapped_column(
        String(64), default="plain_text", nullable=False
    )
    parse_error_code: Mapped[str | None] = mapped_column(
        String(120), nullable=True
    )
    # Defer large pgvector payloads on default entity loads.
    embedding = mapped_column(Vector(1536), deferred=True)

    email: Mapped["Email"] = relationship(back_populates="attachments")
    content_nodes: Mapped[list["ContentNodeRecord"]] = relationship(
        back_populates="attachment"
    )
    content_segments: Mapped[list["ContentSegmentRecord"]] = relationship(
        back_populates="attachment"
    )
    knowledge_graph_edges: Mapped[list["KnowledgeGraphEdgeRecord"]] = relationship(
        back_populates="attachment"
    )


class ContentNodeRecord(Base):
    __tablename__ = "content_nodes"
    __table_args__ = (
        UniqueConstraint("content_node_uid", name="uq_content_nodes_uid"),
        Index(
            "ix_content_nodes_email_source",
            "email_id",
            "source_kind",
            "source_record_uid",
            "ordinal_index",
        ),
        Index("ix_content_nodes_attachment", "attachment_id", "ordinal_index"),
        Index("ix_content_nodes_hash", "content_hash"),
    )

    content_node_id: Mapped[int] = mapped_column(primary_key=True)
    content_node_uid: Mapped[str] = mapped_column(String(64), nullable=False)
    email_id: Mapped[int] = mapped_column(
        ForeignKey("email_records.id"), nullable=False
    )
    attachment_id: Mapped[int | None] = mapped_column(
        ForeignKey("email_attachments.id"), nullable=True
    )
    source_kind: Mapped[str] = mapped_column(String(64), nullable=False)
    source_record_uid: Mapped[str] = mapped_column(String(256), nullable=False)
    parent_node_uid: Mapped[str | None] = mapped_column(String(64), nullable=True)
    node_kind: Mapped[str] = mapped_column(String(64), nullable=False)
    node_path: Mapped[str] = mapped_column(String(512), nullable=False)
    ordinal_index: Mapped[int] = mapped_column(Integer, nullable=False)
    display_label: Mapped[str | None] = mapped_column(String(240), nullable=True)
    safe_text_content: Mapped[str] = mapped_column(Text, default="", nullable=False)
    content_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
        nullable=False,
    )

    email: Mapped["Email"] = relationship(back_populates="content_nodes")
    attachment: Mapped["Attachment | None"] = relationship(
        back_populates="content_nodes"
    )
    segments: Mapped[list["ContentSegmentRecord"]] = relationship(
        back_populates="content_node", cascade="all, delete-orphan"
    )
    outgoing_edges: Mapped[list["KnowledgeGraphEdgeRecord"]] = relationship(
        "KnowledgeGraphEdgeRecord",
        back_populates="source_node",
        foreign_keys="KnowledgeGraphEdgeRecord.source_node_id",
    )
    incoming_edges: Mapped[list["KnowledgeGraphEdgeRecord"]] = relationship(
        "KnowledgeGraphEdgeRecord",
        back_populates="target_node",
        foreign_keys="KnowledgeGraphEdgeRecord.target_node_id",
    )


class ContentSegmentRecord(Base):
    __tablename__ = "content_segments"
    __table_args__ = (
        UniqueConstraint("content_segment_uid", name="uq_content_segments_uid"),
        Index(
            "ix_content_segments_email_source",
            "email_id",
            "source_kind",
            "source_record_uid",
            "ordinal_index",
        ),
        Index("ix_content_segments_attachment", "attachment_id", "ordinal_index"),
        Index("ix_content_segments_node", "content_node_id"),
        Index("ix_content_segments_hash", "content_hash"),
    )

    content_segment_id: Mapped[int] = mapped_column(primary_key=True)
    content_segment_uid: Mapped[str] = mapped_column(String(64), nullable=False)
    email_id: Mapped[int] = mapped_column(
        ForeignKey("email_records.id"), nullable=False
    )
    attachment_id: Mapped[int | None] = mapped_column(
        ForeignKey("email_attachments.id"), nullable=True
    )
    content_node_id: Mapped[int] = mapped_column(
        ForeignKey("content_nodes.content_node_id"), nullable=False
    )
    source_kind: Mapped[str] = mapped_column(String(64), nullable=False)
    source_record_uid: Mapped[str] = mapped_column(String(256), nullable=False)
    segment_kind: Mapped[str] = mapped_column(String(64), nullable=False)
    segment_path: Mapped[str] = mapped_column(String(512), nullable=False)
    ordinal_index: Mapped[int] = mapped_column(Integer, nullable=False)
    heading_path: Mapped[str | None] = mapped_column(String(512), nullable=True)
    safe_text_content: Mapped[str] = mapped_column(Text, nullable=False)
    content_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    word_count: Mapped[int] = mapped_column(Integer, nullable=False)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
        nullable=False,
    )

    email: Mapped["Email"] = relationship(back_populates="content_segments")
    attachment: Mapped["Attachment | None"] = relationship(
        back_populates="content_segments"
    )
    content_node: Mapped["ContentNodeRecord"] = relationship(back_populates="segments")
    outgoing_edges: Mapped[list["KnowledgeGraphEdgeRecord"]] = relationship(
        "KnowledgeGraphEdgeRecord",
        back_populates="source_segment",
        foreign_keys="KnowledgeGraphEdgeRecord.source_segment_id",
    )
    incoming_edges: Mapped[list["KnowledgeGraphEdgeRecord"]] = relationship(
        "KnowledgeGraphEdgeRecord",
        back_populates="target_segment",
        foreign_keys="KnowledgeGraphEdgeRecord.target_segment_id",
    )


class KnowledgeGraphEdgeRecord(Base):
    __tablename__ = "knowledge_graph_edges"
    __table_args__ = (
        UniqueConstraint("edge_uid", name="uq_knowledge_graph_edges_uid"),
        Index(
            "ix_knowledge_graph_edges_email_kind",
            "email_id",
            "edge_kind",
            "ordinal_index",
        ),
        Index("ix_knowledge_graph_edges_attachment", "attachment_id", "edge_kind"),
        Index("ix_knowledge_graph_edges_source_node", "source_node_id"),
        Index("ix_knowledge_graph_edges_target_node", "target_node_id"),
        Index("ix_knowledge_graph_edges_source_segment", "source_segment_id"),
        Index("ix_knowledge_graph_edges_target_segment", "target_segment_id"),
    )

    knowledge_graph_edge_id: Mapped[int] = mapped_column(primary_key=True)
    edge_uid: Mapped[str] = mapped_column(String(64), nullable=False)
    email_id: Mapped[int] = mapped_column(
        ForeignKey("email_records.id"), nullable=False
    )
    attachment_id: Mapped[int | None] = mapped_column(
        ForeignKey("email_attachments.id"), nullable=True
    )
    source_node_id: Mapped[int | None] = mapped_column(
        ForeignKey("content_nodes.content_node_id"), nullable=True
    )
    target_node_id: Mapped[int | None] = mapped_column(
        ForeignKey("content_nodes.content_node_id"), nullable=True
    )
    source_segment_id: Mapped[int | None] = mapped_column(
        ForeignKey("content_segments.content_segment_id"), nullable=True
    )
    target_segment_id: Mapped[int | None] = mapped_column(
        ForeignKey("content_segments.content_segment_id"), nullable=True
    )
    source_kind: Mapped[str] = mapped_column(String(64), nullable=False)
    source_record_uid: Mapped[str] = mapped_column(String(256), nullable=False)
    edge_kind: Mapped[str] = mapped_column(String(64), nullable=False)
    edge_path: Mapped[str] = mapped_column(String(512), nullable=False)
    ordinal_index: Mapped[int] = mapped_column(Integer, nullable=False)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
        nullable=False,
    )

    email: Mapped["Email"] = relationship(back_populates="knowledge_graph_edges")
    attachment: Mapped["Attachment | None"] = relationship(
        back_populates="knowledge_graph_edges"
    )
    source_node: Mapped["ContentNodeRecord | None"] = relationship(
        "ContentNodeRecord",
        back_populates="outgoing_edges",
        foreign_keys=[source_node_id],
    )
    target_node: Mapped["ContentNodeRecord | None"] = relationship(
        "ContentNodeRecord",
        back_populates="incoming_edges",
        foreign_keys=[target_node_id],
    )
    source_segment: Mapped["ContentSegmentRecord | None"] = relationship(
        "ContentSegmentRecord",
        back_populates="outgoing_edges",
        foreign_keys=[source_segment_id],
    )
    target_segment: Mapped["ContentSegmentRecord | None"] = relationship(
        "ContentSegmentRecord",
        back_populates="incoming_edges",
        foreign_keys=[target_segment_id],
    )


class ProjectGraphObjectRecord(Base):
    __tablename__ = "project_graph_objects"
    __table_args__ = (
        UniqueConstraint("object_uid", name="uq_project_graph_objects_uid"),
        Index(
            "ix_project_graph_objects_scope_type_status",
            "user_id",
            "organization_id",
            "workspace_id",
            "object_type",
            "status_code",
        ),
        Index("ix_project_graph_objects_email", "email_id"),
        Index("ix_project_graph_objects_primary_segment", "primary_content_segment_id"),
        Index("ix_project_graph_objects_extractor", "extractor_name", "extractor_version"),
    )

    project_graph_object_id: Mapped[int] = mapped_column(primary_key=True)
    object_uid: Mapped[str] = mapped_column(String(96), nullable=False)
    user_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    organization_id: Mapped[str | None] = mapped_column(String, index=True, nullable=True)
    workspace_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    email_id: Mapped[int] = mapped_column(
        ForeignKey("email_records.id"), nullable=False
    )
    attachment_id: Mapped[int | None] = mapped_column(
        ForeignKey("email_attachments.id"), nullable=True
    )
    primary_content_segment_id: Mapped[int] = mapped_column(
        ForeignKey("content_segments.content_segment_id"), nullable=False
    )
    object_type: Mapped[str] = mapped_column(String(64), nullable=False)
    title: Mapped[str] = mapped_column(String(240), nullable=False)
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    status_code: Mapped[str] = mapped_column(
        String(64), default="candidate", nullable=False
    )
    confidence: Mapped[float] = mapped_column(Float, nullable=False)
    source_segment_uids: Mapped[list[str]] = mapped_column(
        JSON, default=list, nullable=False
    )
    attributes_json: Mapped[dict[str, object]] = mapped_column(
        JSON, default=dict, nullable=False
    )
    extractor_name: Mapped[str] = mapped_column(String(120), nullable=False)
    extractor_version: Mapped[str] = mapped_column(String(64), nullable=False)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
        nullable=False,
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
        onupdate=lambda: datetime.datetime.now(datetime.timezone.utc),
        nullable=False,
    )

    email: Mapped["Email"] = relationship("Email")
    attachment: Mapped["Attachment | None"] = relationship("Attachment")
    primary_content_segment: Mapped["ContentSegmentRecord"] = relationship(
        "ContentSegmentRecord"
    )
    outgoing_edges: Mapped[list["ProjectGraphEdgeRecord"]] = relationship(
        "ProjectGraphEdgeRecord",
        back_populates="source_object",
        foreign_keys="ProjectGraphEdgeRecord.source_object_id",
    )
    incoming_edges: Mapped[list["ProjectGraphEdgeRecord"]] = relationship(
        "ProjectGraphEdgeRecord",
        back_populates="target_object",
        foreign_keys="ProjectGraphEdgeRecord.target_object_id",
    )
    corrections: Mapped[list["ProjectGraphCorrectionRecord"]] = relationship(
        "ProjectGraphCorrectionRecord",
        back_populates="project_object",
        cascade="all, delete-orphan",
    )


class ProjectGraphEdgeRecord(Base):
    __tablename__ = "project_graph_edges"
    __table_args__ = (
        UniqueConstraint("edge_uid", name="uq_project_graph_edges_uid"),
        Index(
            "ix_project_graph_edges_scope_type",
            "user_id",
            "organization_id",
            "workspace_id",
            "edge_type",
        ),
        Index("ix_project_graph_edges_source_object", "source_object_id"),
        Index("ix_project_graph_edges_target_object", "target_object_id"),
        Index("ix_project_graph_edges_primary_segment", "primary_content_segment_id"),
    )

    project_graph_edge_id: Mapped[int] = mapped_column(primary_key=True)
    edge_uid: Mapped[str] = mapped_column(String(96), nullable=False)
    user_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    organization_id: Mapped[str | None] = mapped_column(String, index=True, nullable=True)
    workspace_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    source_uid: Mapped[str] = mapped_column(String(160), nullable=False)
    target_uid: Mapped[str] = mapped_column(String(160), nullable=False)
    edge_type: Mapped[str] = mapped_column(String(80), nullable=False)
    confidence: Mapped[float] = mapped_column(Float, nullable=False)
    source_segment_uids: Mapped[list[str]] = mapped_column(
        JSON, default=list, nullable=False
    )
    source_object_id: Mapped[int | None] = mapped_column(
        ForeignKey("project_graph_objects.project_graph_object_id"),
        nullable=True,
    )
    target_object_id: Mapped[int | None] = mapped_column(
        ForeignKey("project_graph_objects.project_graph_object_id"),
        nullable=True,
    )
    primary_content_segment_id: Mapped[int] = mapped_column(
        ForeignKey("content_segments.content_segment_id"), nullable=False
    )
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
        nullable=False,
    )

    source_object: Mapped["ProjectGraphObjectRecord | None"] = relationship(
        "ProjectGraphObjectRecord",
        back_populates="outgoing_edges",
        foreign_keys=[source_object_id],
    )
    target_object: Mapped["ProjectGraphObjectRecord | None"] = relationship(
        "ProjectGraphObjectRecord",
        back_populates="incoming_edges",
        foreign_keys=[target_object_id],
    )
    primary_content_segment: Mapped["ContentSegmentRecord"] = relationship(
        "ContentSegmentRecord"
    )


class ProjectGraphCorrectionRecord(Base):
    __tablename__ = "project_graph_corrections"
    __table_args__ = (
        UniqueConstraint("correction_uid", name="uq_project_graph_corrections_uid"),
        Index(
            "ix_project_graph_corrections_scope_time",
            "user_id",
            "organization_id",
            "workspace_id",
            "created_at",
        ),
        Index("ix_project_graph_corrections_object", "project_graph_object_id"),
    )

    project_graph_correction_id: Mapped[int] = mapped_column(primary_key=True)
    correction_uid: Mapped[str] = mapped_column(
        String(96),
        default=lambda: f"project_correction_{uuid.uuid4().hex}",
        nullable=False,
    )
    project_graph_object_id: Mapped[int] = mapped_column(
        ForeignKey("project_graph_objects.project_graph_object_id"),
        nullable=False,
    )
    user_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    organization_id: Mapped[str | None] = mapped_column(String, index=True, nullable=True)
    workspace_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    actor_user_id: Mapped[str] = mapped_column(String, nullable=False)
    correction_action: Mapped[str] = mapped_column(String(64), nullable=False)
    before_json: Mapped[dict[str, object]] = mapped_column(
        JSON, default=dict, nullable=False
    )
    after_json: Mapped[dict[str, object]] = mapped_column(
        JSON, default=dict, nullable=False
    )
    rationale: Mapped[str | None] = mapped_column(Text, nullable=True)
    source_segment_uids: Mapped[list[str]] = mapped_column(
        JSON, default=list, nullable=False
    )
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
        nullable=False,
    )

    project_object: Mapped["ProjectGraphObjectRecord"] = relationship(
        "ProjectGraphObjectRecord",
        back_populates="corrections",
    )


class TenantConfig(Base):
    __tablename__ = "tenant_configs"

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[str] = mapped_column(String, index=True)
    organization_id: Mapped[str | None] = mapped_column(
        String,
        index=True,
        nullable=True,
    )

    # Email settings
    smtp_server: Mapped[str | None] = mapped_column(String, nullable=True)
    smtp_port: Mapped[int | None] = mapped_column(nullable=True)
    smtp_username: Mapped[str | None] = mapped_column(String, nullable=True)
    smtp_password: Mapped[str | None] = mapped_column(EncryptedString, nullable=True)
    imap_server: Mapped[str | None] = mapped_column(String, nullable=True)
    imap_port: Mapped[int | None] = mapped_column(nullable=True)
    imap_username: Mapped[str | None] = mapped_column(String, nullable=True)
    imap_password: Mapped[str | None] = mapped_column(EncryptedString, nullable=True)
    pop3_server: Mapped[str | None] = mapped_column(String, nullable=True)
    pop3_port: Mapped[int | None] = mapped_column(nullable=True)
    pop3_username: Mapped[str | None] = mapped_column(String, nullable=True)
    pop3_password: Mapped[str | None] = mapped_column(EncryptedString, nullable=True)

    # OAuth and Third Party Settings
    oauth_client_id: Mapped[str | None] = mapped_column(String, nullable=True)
    oauth_client_secret: Mapped[str | None] = mapped_column(
        EncryptedString, nullable=True
    )
    oauth_redirect_uri: Mapped[str | None] = mapped_column(String, nullable=True)

    openai_api_key: Mapped[str | None] = mapped_column(EncryptedString, nullable=True)
    google_client_id: Mapped[str | None] = mapped_column(String, nullable=True)
    google_client_secret: Mapped[str | None] = mapped_column(
        EncryptedString, nullable=True
    )

    # Batch-tolerant embedding routing via contextual-orchestrator. All config
    # here lives in the Fernet DB, never in os.getenv. The orchestrator is the
    # routing/cost hub: naruon submits bulk embeddings to it and it forwards to
    # pg-llm-batch and records cost. The bearer token is a secret so it is stored
    # EncryptedString (Fernet at rest); the base URL is not a secret but is
    # SSRF-guarded + allowlisted at call time. batch_local_dsn is an optional
    # offline-dev fallback DSN for a local pg-llm-batch package (also a secret).
    batch_embedding_enabled: Mapped[bool] = mapped_column(
        Boolean, default=False, nullable=False
    )
    batch_orchestrator_base_url: Mapped[str | None] = mapped_column(
        String, nullable=True
    )
    batch_orchestrator_token: Mapped[str | None] = mapped_column(
        EncryptedString, nullable=True
    )
    batch_orchestrator_endpoint: Mapped[str | None] = mapped_column(
        String, nullable=True
    )
    batch_embedding_model: Mapped[str | None] = mapped_column(String, nullable=True)
    batch_local_dsn: Mapped[str | None] = mapped_column(EncryptedString, nullable=True)
    # Cost-attribution dimensions forwarded to the orchestrator ledger so batch
    # embedding cost is attributed across the full dimension set the hub expects
    # (service / team / group / company, on top of the source / organization /
    # user observability keys). Not secrets, so plain String. company falls back
    # to organization_id at call time when left unset.
    batch_attribution_service: Mapped[str | None] = mapped_column(String, nullable=True)
    batch_attribution_team: Mapped[str | None] = mapped_column(String, nullable=True)
    batch_attribution_group: Mapped[str | None] = mapped_column(String, nullable=True)
    batch_attribution_company: Mapped[str | None] = mapped_column(String, nullable=True)

    def __repr__(self) -> str:
        return (
            f"<TenantConfig(id={self.id}, user_id='{self.user_id}', "
            f"organization_id='{self.organization_id}', "
            f"smtp_server='{self.smtp_server}', imap_server='{self.imap_server}', "
            f"has_smtp_password={self.smtp_password is not None}, "
            f"has_imap_password={self.imap_password is not None}, "
            f"has_pop3_password={self.pop3_password is not None}, "
            f"has_oauth_secret={self.oauth_client_secret is not None}, "
            f"has_openai_key={self.openai_api_key is not None}, "
            f"has_google_secret={self.google_client_secret is not None})>"
        )


Index(
    "uq_tenant_configs_owner_scope",
    TenantConfig.user_id,
    func.coalesce(TenantConfig.organization_id, ""),
    unique=True,
)


class SenderRelationship(Base):
    __tablename__ = "sender_relationships"

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    organization_id: Mapped[str | None] = mapped_column(
        String,
        index=True,
        nullable=True,
    )
    sender_email: Mapped[str] = mapped_column(String, index=True, nullable=False)
    parent_sender_email: Mapped[str | None] = mapped_column(String, index=True, nullable=True)
    source_message_id: Mapped[str | None] = mapped_column(String, index=True, nullable=True)
    source_thread_id: Mapped[str | None] = mapped_column(String, index=True, nullable=True)
    relationship_type: Mapped[str] = mapped_column(String, nullable=False)
    confidence_score: Mapped[float] = mapped_column(default=1.0)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
        onupdate=lambda: datetime.datetime.now(datetime.timezone.utc),
    )
    __table_args__ = (
        Index(
            "uq_sender_relationships_scope_source",
            "user_id",
            func.coalesce(organization_id, ""),
            "sender_email",
            func.coalesce(source_message_id, ""),
            func.coalesce(source_thread_id, ""),
            unique=True,
        ),
    )


class CaldavAccount(Base):
    __tablename__ = "caldav_accounts"

    id: Mapped[int] = mapped_column("account_id", primary_key=True)
    user_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    server_url: Mapped[str] = mapped_column(String, nullable=False)
    username: Mapped[str] = mapped_column(String, nullable=False)
    credentials_encrypted: Mapped[str] = mapped_column(EncryptedString, nullable=False)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
    )


class CarddavAccount(Base):
    __tablename__ = "carddav_accounts"

    account_id: Mapped[int] = mapped_column("account_id", primary_key=True)
    source_uid: Mapped[str] = mapped_column(
        String,
        unique=True,
        index=True,
        default=lambda: f"carddav_src_{uuid.uuid4().hex}",
        nullable=False,
    )
    user_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    organization_id: Mapped[str | None] = mapped_column(String, index=True, nullable=True)
    workspace_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    server_url: Mapped[str] = mapped_column(String, nullable=False)
    # New tables use two-word snake_case column names; the Python attribute
    # stays `username` for symmetry with the WebdavAccount mapper.
    username: Mapped[str] = mapped_column("account_username", String, nullable=False)
    credentials_encrypted: Mapped[str] = mapped_column(EncryptedString, nullable=False)
    discovery_source: Mapped[str | None] = mapped_column(String, nullable=True)
    account_index: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    writeback_enabled: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
        nullable=False,
    )


class CalendarWritebackSource(Base):
    __tablename__ = "calendar_writeback_sources"

    source_uid: Mapped[str] = mapped_column(String, primary_key=True)
    user_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    organization_id: Mapped[str | None] = mapped_column(String, index=True, nullable=True)
    workspace_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    account_ref: Mapped[str | None] = mapped_column(String, nullable=True)
    provider_name: Mapped[str] = mapped_column(String, nullable=False)
    source_protocol: Mapped[str] = mapped_column(String, nullable=False)
    source_host: Mapped[str] = mapped_column(String, nullable=False)
    writeback_enabled: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    etag_value: Mapped[str | None] = mapped_column(String, nullable=True)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
    )
    __table_args__ = (
        Index(
            "ix_calendar_writeback_sources_scope",
            "user_id",
            "organization_id",
            "source_protocol",
        ),
    )


class ReplyTracker(Base):
    __tablename__ = "reply_trackers"

    id: Mapped[int] = mapped_column("tracker_id", primary_key=True)
    user_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    message_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    status_code: Mapped[str] = mapped_column(String, default="waiting", index=True)
    follow_up_date: Mapped[datetime.datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
        onupdate=lambda: datetime.datetime.now(datetime.timezone.utc),
    )


class WebdavAccount(Base):
    __tablename__ = "webdav_accounts"

    id: Mapped[int] = mapped_column("account_id", primary_key=True)
    source_uid: Mapped[str] = mapped_column(
        String,
        unique=True,
        index=True,
        default=lambda: f"webdav_src_{uuid.uuid4().hex}",
        nullable=False,
    )
    user_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    organization_id: Mapped[str | None] = mapped_column(String, index=True, nullable=True)
    workspace_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    server_url: Mapped[str] = mapped_column(String, nullable=False)
    username: Mapped[str] = mapped_column(String, nullable=False)
    credentials_encrypted: Mapped[str] = mapped_column(EncryptedString, nullable=False)
    writeback_enabled: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    etag_value: Mapped[str | None] = mapped_column(String, nullable=True)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
    )


class ProjectFolder(Base):
    __tablename__ = "project_folders"

    id: Mapped[int] = mapped_column("folder_id", primary_key=True)
    folder_uid: Mapped[str] = mapped_column(
        String,
        unique=True,
        index=True,
        default=lambda: f"webdav_folder_{uuid.uuid4().hex}",
        nullable=False,
    )
    user_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    organization_id: Mapped[str | None] = mapped_column(String, index=True, nullable=True)
    project_name: Mapped[str] = mapped_column(String, index=True, nullable=False)
    webdav_path: Mapped[str] = mapped_column(String, nullable=False)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
    )


class Workspace(Base):
    __tablename__ = "workspace_entities"

    workspace_id: Mapped[str] = mapped_column(String, primary_key=True, default=lambda: f"workspace_{uuid.uuid4().hex}")
    workspace_name: Mapped[str] = mapped_column(String, nullable=False)
    workspace_domain: Mapped[str | None] = mapped_column(String, nullable=True)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
    )

    workspace_documents: Mapped[list["Document"]] = relationship(
        back_populates="workspace_entity"
    )

class Document(Base):
    __tablename__ = "workspace_documents"

    document_id: Mapped[str] = mapped_column(String, primary_key=True, default=lambda: f"doc_{uuid.uuid4().hex}")
    workspace_id: Mapped[str] = mapped_column(String, ForeignKey("workspace_entities.workspace_id"), index=True, nullable=False)
    # Owning organization (nullable for personal-scope docs). Persisted so the
    # NewsDOM recognition worker can resolve the org's provider without joining
    # through the (org-less) workspace entity.
    organization_id: Mapped[str | None] = mapped_column(String, index=True, nullable=True)
    document_name: Mapped[str] = mapped_column(String, nullable=False)
    document_type: Mapped[str] = mapped_column(String, nullable=False)
    document_content: Mapped[str] = mapped_column(Text, nullable=True)
    document_status: Mapped[str] = mapped_column(String, default="pending")
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.datetime.now(datetime.timezone.utc),
    )

    workspace_entity: Mapped["Workspace"] = relationship(
        back_populates="workspace_documents"
    )
